In [1]:
import pandas as pd

In [2]:
url ="https://raw.githubusercontent.com/Jose-guerra2002/etl-data-pipeline2510832022/refs/heads/main/data/raw/D_empleados.csv"
df = pd.read_csv(url)
df.head()

  id_empleado          nombre id_departamento fecha_ingreso
0       EM400    Marta Romero             D10    2023-09-12
1       EM401    José Ramírez             D15    2022-09-26
2       EM402   Miguel Romero             D10    2020-02-02
3       EM403     Elena Rivas             D99    2020-01-14
4       EM404  Fernando Rivas             D13    2022-12-25

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_empleado      136 non-null    object
 1   nombre           136 non-null    object
 2   id_departamento  129 non-null    object
 3   fecha_ingreso    132 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB

id_empleado        0
nombre             0
id_departamento    7
fecha_ingreso      4
dtype: int64

In [4]:
def limpiar_datos(df):
      df = df.copy()
      df.columns = df.columns.str.strip().str.lower()
      for col in df.select_dtypes(include='object'):
          df[col] = df[col].astype(str).str.strip()
      print("DataFrame limpio:")
      display(df.head())
      print(df.info())
      return df
empleados = limpiar_datos(df)

DataFrame limpio:

  id_empleado          nombre id_departamento fecha_ingreso
0       EM400    Marta Romero             D10    2023-09-12
1       EM401    José Ramírez             D15    2022-09-26
2       EM402   Miguel Romero             D10    2020-02-02
3       EM403     Elena Rivas             D99    2020-01-14
4       EM404  Fernando Rivas             D13    2022-12-25

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_empleado      136 non-null    object
 1   nombre           136 non-null    object
 2   id_departamento  136 non-null    object
 3   fecha_ingreso    136 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB
None

In [5]:
def limpiar_fechas(df):
      df = df.copy()
      df['fecha_ingreso'] = df['fecha_ingreso'].str.replace('/',
  '-', regex=False)
      df['fecha_ingreso'] = pd.to_datetime(df['fecha_ingreso'],
  errors='coerce')
      return df
empleados = limpiar_fechas(empleados)
empleados.head()

  id_empleado          nombre id_departamento fecha_ingreso
0       EM400    Marta Romero             D10    2023-09-12
1       EM401    José Ramírez             D15    2022-09-26
2       EM402   Miguel Romero             D10    2020-02-02
3       EM403     Elena Rivas             D99    2020-01-14
4       EM404  Fernando Rivas             D13    2022-12-25

In [6]:
def limpiar_duplicados(df):
      df = df.copy()
      df = df.drop_duplicates()
      print("Shape sin duplicados:")
      print(df.shape)
      return df
empleados = limpiar_duplicados(empleados)

Shape sin duplicados:
(130, 4)

In [7]:
def filtrar_validos(df):
      validos = df.dropna(subset=['id_departamento',
  'fecha_ingreso']).copy()
      validos = validos[validos['id_departamento'] != 'D99'].copy()
      print("Datos validos:")
      display(validos.head())
      print(validos.shape)
      return validos
validos_empleados = filtrar_validos(empleados)

Datos validos:

  id_empleado           nombre id_departamento fecha_ingreso
0       EM400     Marta Romero             D10    2023-09-12
1       EM401     José Ramírez             D15    2022-09-26
2       EM402    Miguel Romero             D10    2020-02-02
4       EM404   Fernando Rivas             D13    2022-12-25
5       EM405  Diego Hernández             D12    2023-02-03

(116, 4)

In [8]:
def identificar_rechazo(df):
      rechazados = df[
          df[['id_departamento',
  'fecha_ingreso']].isnull().any(axis=1) |
          (df['id_departamento'] == 'D99')
      ].copy()
      rechazados['motivo_rechazo'] = rechazados.apply(
          lambda x: 'Departamento invalido' if x['id_departamento']
  == 'D99'
          else 'Falta id_departamento' if
  pd.isnull(x['id_departamento'])
          else 'Falta fecha_ingreso' if
  pd.isnull(x['fecha_ingreso'])
          else 'Otro',
          axis=1
      )
      print("Datos rechazados:")
      display(rechazados.head())
      print(rechazados.shape)
      return rechazados
rechazados_empleados = identificar_rechazo(empleados)

Datos rechazados:

,id_empleado,nombre,id_departamento,fecha_ingreso,motivo_rechazo
3,EM403,Elena Rivas,D99,2020-01-14,Departamento invalido
6,EM406,Adriana Santos,D99,2022-04-22,Departamento invalido
19,EM419,Elena Ramírez,D16,NaT,Falta fecha_ingreso
23,EM423,Daniela López,D99,2020-07-16,Departamento invalido
47,EM447,Luis Mendoza,D14,NaT,Falta fecha_ingreso

(14, 5)

In [9]:
def exportar_empleados(validos, rechazados):
      validos.to_csv("D_empleados_curated.csv", index=False)
      rechazados.to_csv("D_empleados_rejects.csv", index=False)
      print("Archivos exportados:")
      print("- D_empleados_curated.csv")
      print("- D_empleados_rejects.csv")
exportar_empleados(validos_empleados, rechazados_empleados)

Archivos exportados:
- D_empleados_curated.csv
- D_empleados_rejects.csv

In [10]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 36.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [11]:
from sqlalchemy import create_engine
import pandas as pd

In [12]:
database_url = "postgresql://etl_seguros_6rdr_user:BLDMfhhALJNiooAJN3zJErFDUwEYk7xM@dpg-d6quauh5pdvs73bhia4g-a.virginia-postgres.render.com/etl_seguros_6rdr"

In [13]:
engine = create_engine(database_url)

In [14]:
test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [23]:
validos_empleados.to_sql(
      'd_empleados_curated',
      engine,
      if_exists='replace',
      index=False
  )

116

In [16]:
rechazados_empleados.to_sql(
      'D_empleados_rejects',
      engine,
      if_exists='replace',
      index=False
  )

14

In [24]:
pd.read_sql("SELECT * FROM d_empleados_curated LIMIT 10", engine)

  id_empleado           nombre id_departamento fecha_ingreso
0       EM400     Marta Romero             D10    2023-09-12
1       EM401     José Ramírez             D15    2022-09-26
2       EM402    Miguel Romero             D10    2020-02-02
3       EM404   Fernando Rivas             D13    2022-12-25
4       EM405  Diego Hernández             D12    2023-02-03
5       EM407    Sofía Mendoza             D13    2020-01-25
6       EM408     María Torres             D14    2020-02-04
7       EM409      Paola Rivas             D11    2022-12-20
8       EM410   Andrés Ramírez             D10    2024-01-19
9       EM411  Natalia Vásquez             D14    2021-07-16