In [1]:
import pandas as pd

In [2]:
url ="https://raw.githubusercontent.com/Jose-guerra2002/etl-data-pipeline2510832022/refs/heads/main/data/raw/D_salarios.csv"
df = pd.read_csv(url)
df.head()

  id_salario id_empleado  salario    bono
0      S6000       EM432   586.98  281.04
1      S6001       EM454      NaN  473.55
2      S6002       EM406  1583.76  248.13
3      S6003       EM456   1647.0  190.26
4      S6004       EM525  2750.51   81.52

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_salario   136 non-null    object
 1   id_empleado  130 non-null    object
 2   salario      130 non-null    object
 3   bono         132 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB

id_salario     0
id_empleado    6
salario        6
bono           4
dtype: int64

In [5]:
def limpiar_datos(df):
      df = df.copy()
      df.columns = df.columns.str.strip().str.lower()
      for col in df.select_dtypes(include='object'):
          df[col] = df[col].astype(str).str.strip()
      print("DataFrame limpio:")
      display(df.head())
      print(df.info())
      return df

salarios = limpiar_datos(df)

DataFrame limpio:

  id_salario id_empleado  salario    bono
0      S6000       EM432   586.98  281.04
1      S6001       EM454      nan  473.55
2      S6002       EM406  1583.76  248.13
3      S6003       EM456   1647.0  190.26
4      S6004       EM525  2750.51   81.52

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_salario   136 non-null    object
 1   id_empleado  136 non-null    object
 2   salario      136 non-null    object
 3   bono         136 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB
None

In [6]:
def limpiar_salario(df):
      df = df.copy()
      df['salario'] = df['salario'].str.replace('$', '',
  regex=False).str.strip()
      df['salario'] = pd.to_numeric(df['salario'], errors='coerce')
      return df
salarios = limpiar_salario(salarios)
salarios.head()

  id_salario id_empleado  salario    bono
0      S6000       EM432   586.98  281.04
1      S6001       EM454      NaN  473.55
2      S6002       EM406  1583.76  248.13
3      S6003       EM456  1647.00  190.26
4      S6004       EM525  2750.51   81.52

In [7]:
def limpiar_bono(df):
      df = df.copy()
      df['bono'] = df['bono'].str.replace('USD', '',
  regex=False).str.strip()
      df['bono'] = df['bono'].replace('sin bono', pd.NA)
      df['bono'] = pd.to_numeric(df['bono'], errors='coerce')
      return df
salarios = limpiar_bono(salarios)
salarios.head()

  id_salario id_empleado  salario    bono
0      S6000       EM432   586.98  281.04
1      S6001       EM454      NaN  473.55
2      S6002       EM406  1583.76  248.13
3      S6003       EM456  1647.00  190.26
4      S6004       EM525  2750.51   81.52

In [8]:
def limpiar_duplicados(df):
      df = df.copy()
      df = df.drop_duplicates()
      print("Shape sin duplicados:")
      print(df.shape)
      return df
salarios = limpiar_duplicados(salarios)

Shape sin duplicados:
(130, 4)

In [9]:
def filtrar_validos(df):
      validos = df.dropna(subset=['id_empleado', 'salario']).copy()
      print("Datos validos:")
      display(validos.head())
      print(validos.shape)
      return validos
validos_salarios = filtrar_validos(salarios)

Datos validos:

  id_salario id_empleado  salario    bono
0      S6000       EM432   586.98  281.04
2      S6002       EM406  1583.76  248.13
3      S6003       EM456  1647.00  190.26
4      S6004       EM525  2750.51   81.52
5      S6005       EM411  3251.20  393.10

(124, 4)

In [10]:
def identificar_rechazo(df):
      rechazados = df[df[['id_empleado',
  'salario']].isnull().any(axis=1)].copy()
      rechazados['motivo_rechazo'] = rechazados.apply(
          lambda x: 'Falta id_empleado' if
  pd.isnull(x['id_empleado'])
          else 'Falta salario' if pd.isnull(x['salario'])
          else 'Otro',
          axis=1
      )
      print("Datos rechazados:")
      display(rechazados.head())
      print(rechazados.shape)
      return rechazados

rechazados_salarios = identificar_rechazo(salarios)

Datos rechazados:

   id_salario id_empleado  salario    bono motivo_rechazo
1       S6001       EM454      NaN  473.55  Falta salario
34      S6034       EM424      NaN  398.34  Falta salario
45      S6045       EM456      NaN  153.39  Falta salario
77      S6077       EM498      NaN     NaN  Falta salario
85      S6085       EM418      NaN  134.27  Falta salario

(6, 5)

In [11]:
def exportar_salarios(validos, rechazados):
      validos.to_csv("D_salarios_curated.csv", index=False)
      rechazados.to_csv("D_salarios_rejects.csv", index=False)
      print("Archivos exportados:")
      print("- D_salarios_curated.csv")
      print("- D_salarios_rejects.csv")

exportar_salarios(validos_salarios, rechazados_salarios)

Archivos exportados:
- D_salarios_curated.csv
- D_salarios_rejects.csv

In [12]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 62.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [13]:
from sqlalchemy import create_engine
import pandas as pd

In [14]:
database_url = "postgresql://etl_seguros_6rdr_user:BLDMfhhALJNiooAJN3zJErFDUwEYk7xM@dpg-d6quauh5pdvs73bhia4g-a.virginia-postgres.render.com/etl_seguros_6rdr"

In [15]:
engine = create_engine(database_url)

In [16]:
test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [17]:
validos_salarios.to_sql(
      'D_salarios_curated',
      engine,
      if_exists='replace',
      index=False
  )

124

In [18]:
rechazados_salarios.to_sql(
      'D_salarios_rejects',
      engine,
      if_exists='replace',
      index=False
  )

6